source 'https://github.com/CocoaPods/Specs.git'

use_frameworks!

target 'CloudBridge', :exclusive => true do
  pod "CloudBridge", :path => "../"

  pod 'Expecta', '~> 0.3.1'
  pod 'OCMock', '~> 3.1.1'
end
